//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpellCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpellCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;WordList&gt;
        ///    &lt;words&gt;
        ///        &lt;string&gt;a&lt;/string&gt;
        ///        &lt;string&gt;aa&lt;/string&gt;
        ///        &lt;string&gt;aaa&lt;/string&gt;
        ///        &lt;string&gt;aah&lt;/string&gt;
        ///        &lt;string&gt;aahed&lt;/string&gt;
        ///        &lt;string&gt;aahing&lt;/string&gt;
        ///        &lt;string&gt;aahs&lt;/string&gt;
        ///        &lt;string&gt;aal&lt;/string&gt;
        ///        &lt;string&gt;aalii&lt;/string&gt;
        ///        &lt;string&gt;aaliis&lt;/string&gt;
        ///        &lt;string&gt;aals&lt;/string&gt;
        ///        &lt;string&gt;aam&lt;/string&gt;
        ///        &lt;string&gt;aani&lt;/string&gt;
        ///        &lt;string&gt;aardvark&lt;/string&gt;
        ///        &lt;str [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words_xml {
            get {
                return ResourceManager.GetString("words.xml", resourceCulture);
            }
        }
    }
}
